name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          args: --timeout=10m